<?php
$this->headTitle('게시글 수정');
?>
<script type="text/javascript">
    $(document).ready(function() {
    
    });
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 수정 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        게시판 글을 수정합니다.
    </div>
</div>