<?php
$this->headTitle('게시글 리스트');
?>
<script type="text/javascript">
//상단 바의 유저 이름을 클릭했을 경우, 수정 창 출력
$(".user-info").on("click", function() {
    var userId = $(this).data('userId');
    var position = <?php echo $this->position; ?>;
    //최종 관리자는 회원정보 수정이 불가능하므로 alert 창 출력
    if (position == <?php echo Was_Member::POWER_MASTER; ?>) {
        alert("최종관리자는 회원 정보를 수정할 수 없습니다");
        return false;
    }
    //팝업창 크기
    var popUpWidth = 500
    var popUpHeight = 555;
    //팝업창 위치 조절
    var popUpX = (document.body.offsetWidth / 2) - (popUpWidth / 2);
    //듀얼 모니터인 경우 넣어줘야함.
    popUpX += window.screenLeft;
    var popUpY = (window.screen.height / 2) - (popUpHeight / 2);
    
    window.open('/manage/modify?userId=' + userId, '회원정보수정', 'scrollbars=no, resizable=no, width=' + popUpWidth + ', height=' + popUpHeight + ', left='+ popUpX + ',top='+ popUpY);
});
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 리스트 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        등록 된 게시글을 조회하는 페이지 입니다. </br>
        등록 된 글은 조회, 수정 및 삭제 할 수 있습니다.
    </div>
</div>
<div class="col-sm-12 list-body">
    <?php echo $this->form->render(); ?>
    <div class="board-SearchCnt"><?php echo number_format(0) . " / " . number_format(1000) . " 건";?></div>
    <div class="write-btn-div">
        <?php echo $this->FormButton('write-btn', '작 성', array('class' => 'write-btn')); ?>
    </div>
</div>
