<?php
$this->headTitle('게시글 리스트');
?>
<script type="text/javascript">
$(document).ready(function() {
    //상단 바의 유저 이름을 클릭했을 경우, 수정 창 출력
    $(".user-info").on("click", function() {
        var userId = $(this).data('userId');
        var position = <?php echo $this->position; ?>;
        //최종 관리자는 회원정보 수정이 불가능하므로 alert 창 출력
        if (position == <?php echo Was_Member::POWER_MASTER; ?>) {
            alert("최종관리자는 회원 정보를 수정할 수 없습니다");
            return false;
        }
        //팝업창 크기
        var popUpWidth = 500
        var popUpHeight = 555;
        //팝업창 위치 조절
        var popUpX = (document.body.offsetWidth / 2) - (popUpWidth / 2);
        //듀얼 모니터인 경우 넣어줘야함.
        popUpX += window.screenLeft;
        var popUpY = (window.screen.height / 2) - (popUpHeight / 2);
        
        window.open('/manage/modify?userId=' + userId, '회원정보수정', 'scrollbars=no, resizable=no, width=' + popUpWidth + ', height=' + popUpHeight + ', left='+ popUpX + ',top='+ popUpY);
    });

    $(".board-search").on("submit", function() {
        $("#search-isSearch").val(1);
    });
});
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 리스트 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        등록 된 게시글을 조회하는 페이지 입니다. </br>
        등록 된 글은 조회, 수정 및 삭제 할 수 있습니다.
    </div>
</div>
<div class="col-sm-12 list-body">
    <?php echo $this->form->render(); ?>
    <div class="board-SearchCnt"><?php echo number_format(0) . " / " . number_format(1000) . " 건";?></div>
    <div class="write-btn-div">
        <?php echo $this->FormButton('write-btn', '작 성', array('class' => 'write-btn')); ?>
    </div>
    <table class="table-design">
        <thead class="add-top-line">
            <tr>
                <th class="col-sm-1">번호</th>
                <th class="col-sm-5">제목</th>
                <th class="col-sm-2">작성자</th>
                <th class="col-sm-2">작성일자</th>
                <th class="col-sm-1">조회수</th>
                <th class="col-sm-1">작업</th>
            </tr>
        </thead>
        <tbody>
        <?php 
            foreach ($this->paginator as $items) {
        ?>
            <tr class="add-bottom-line">
                <td><?php echo $items['pk']; ?></td>
                <td class="text-align-left"><?php echo $items['title']; ?></td>
                <td><?php echo $items['writer']; ?></td>
                <td><?php echo $items['insertTime']; ?></td>
                <td><?php echo $items['views']; ?></td>
                <td>
                <?php echo $this->FormButton('read-board', '조 회', array('class' => 'read-button'));?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php 
        echo $this->paginationControl($this->paginator, null, null, array('searchForm' => array(
            'category'      => $this->form->search->category->getValue(),
            'search'        => $this->form->search->search->getValue()
        )));
    ?>
</div>
