<?php
$this->headTitle('게시글 리스트');
?>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 리스트 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        등록 된 게시글을 조회하는 페이지 입니다. </br>
        등록 된 글은 조회, 수정 및 삭제 할 수 있습니다.
    </div>
</div>
