<?php
$fileArray = $this->fileArray;
?>
<script type="text/javascript">
$(document).ready(function() {
    $('.close-popup').on('click', function() {
        window.close();
    });
});
</script>
<img src="data:image;base64, <?php echo $fileArray['content']; ?>" alt="image" style="width: 500px; height: 500px;">
<div class='file-download-div'>
    <a href="<?php echo $this->url(array('controller' => 'board', 'action' => 'file-download')); ?>?filePk=<?php echo $fileArray['pk']?>">
    <?php 
        echo $this->FormButton('file-download', '파일 다운로드', array('class' => 'file-download'));
    ?>
    </a>
</div>