<?php
$board = $this->board;
$session = Zend_Session::namespaceGet('Was_Auth');
?>
<script type="text/javascript">
    $(document).ready(function() {
        <?php if (isset($this->boardResult)) : ?>
        var result = <?php echo $this->boardResult ? 'true' : 'false';?>;
        var message = '<?php echo $this->boardMessage; ?>';
        
        if (!result) {
            alert(message);
            window.location.href = '<?php echo $this->url(array('controller' => 'board', 'action' => 'list'))?>';
        }
        <?php endif; ?>
    });
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 조회 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        게시판 글을 조회합니다.
    </div>
</div>
<div class="view-box">
    <div class="page-header-custom">
        <?php echo $board['title']; ?>
        <div class="info">
            <small class="space writer-info">작성자 &emsp; &emsp; : <?php echo $board['writer']; ?></small>
        </div>
    </div>
    <div class="text-box">
        <?php echo nl2br($board['content']); ?>
    </div>
    <div class="file-info">
         
    </div>
    <div class="time-info">
         <div class="time-left"><strong>등록시간 &emsp; &nbsp; &nbsp; &nbsp; :</strong>&nbsp;&nbsp;<?php echo $board['insertTime']; ?></div>
         <div class="time-right"><strong>마지막 수정시간 :</strong>&nbsp; <?php echo $board['updateTime']; ?></div>
    </div>
    <div class="reply">
        <div class='reply-title'>댓 &nbsp; 글</div>
        <table class="col-sm-12">
            <thead>
                <tr>
                    <th class="col-sm-2"></th>
                    <th class="col-sm-7"></th>
                    <th class="col-sm-2"></th>
                    <th class="col-sm-1"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                   <td><strong>· 아무개 </strong></td>
                   <td>댓글1, 가나다라마바사</td>
                   <td>2020-02-06-17:15:20</td>
                   <td>
                       <?php echo $this->FormButton('remove-reply', 'X', array('class' => 'remove-reply-btn')); ?>
                   </td>
                </tr>
            </tbody>
        </table>
    </div>
    <form class="reply-form" method="<?php echo $this->replyForm->getMethod(); ?>">
        <?php echo $this->replyForm->memberPk; ?>
        <?php echo $this->replyForm->name; ?>
        <?php echo $this->replyForm->content; ?>
        <?php echo $this->replyForm->submit; ?>
    </form>
    <div class="view-page-button">
        <?php
        if (($session['storage']->pk == $board['memberPk']) || ($session['storage']->pk == 1)) {
            echo $this->FormButton('delet-btn', '삭 제', array('class' => 'delete-btn', 'data-pk' => $board['pk']));
        }
        ?>
        <div class="button-right">
            <?php if ($session['storage']->pk == $board['memberPk']) {?>
                <input type="submit" class="submit-btn" value="수 &emsp; 정">
            <?php } ?>
            <input type="button" class="cancle-btn" value="닫 &emsp; 기">
        </div>
    </div>
</div>