<?php
$board = $this->board;
$replys = $this->replys;
$files = $this->files;
$photo = array('jpg', 'jpeg', 'png', 'gif');

$session = Zend_Session::namespaceGet('Was_Auth');
$memberTabe = new Was_Member_Table_Member();
?>
<script type="text/javascript">
    $(document).ready(function() {
        <?php if (isset($this->boardResult)) : ?>
        var result = <?php echo $this->boardResult ? 'true' : 'false';?>;
        var message = '<?php echo $this->boardMessage; ?>';
        
        if (!result) {
            alert(message);
            window.location.href = '<?php echo $this->url(array('controller' => 'board', 'action' => 'list'))?>';
        }
        <?php endif; ?>
        
        $('.cancle-btn').on('click', function() {
            var url = new URL('<?php echo $_SERVER['HTTP_REFERER']; ?>');
            
            if (url.pathname == '/board/write' || url.pathname == '/board/view') {
                window.location.href = '<?php echo $this->url(array('controller' => 'board', 'action' => 'list'))?>';
            } else {
                window.location.href = '<?php echo $_SERVER['HTTP_REFERER']; ?>'
            }
        });
        
        $('.delete-btn').on('click', function() {
            var pk = $(this).data('pk');
            
            if (confirm('정말 게시글을 삭제하시겠습니까?')) {
                $.ajax({
                    url: "/board/delete-board",
                    method: "POST",
                    data: {"pk": pk},
                    dataType: "json",
                    success: function(receive) {
                        alert(receive.message);
                        if (receive.result == true) {
                            window.location.href = '<?php echo $this->url(array('controller' => 'board', 'action' => 'list'));?>';
                        } else {
                            window.location.reload();
                        }
                    }
                });
            } else {
                alert('삭제를 취소하셨습니다.');
            }
        });
        
        $('.reply-submit').on('click', function () {
            var boardPk = $(this).data('boardPk');
            var memberPk = $(this).data('memberPk');
            var content = $('.reply-content').val();
            var contentLength = $('.reply-content').val().length;
            
            if (contentLength > 100) {
                alert('댓글은 100자 이하까지만 작성 가능합니다.');
                $('.reply-content').focus();
            } else if (!content) {
                alert('댓글 내용을 작성해주세요.');
            } else {
                $.ajax({
                    url: "/board/write-reply",
                    method: "POST",
                    data: {"boardPk": boardPk, "memberPk": memberPk, "content": content},
                    dataType: "json",
                    success: function(receive) {
                        alert(receive.message);
                        if (receive.result == true) {
                            window.location.reload();
                        } else {
                            $('.reply-content').focus();
                        }
                    }
                });
            }
        });
        
        $('.remove-reply-btn').on('click', function() {
            var replyPk = $(this).data('replyPk');
            
            if (confirm('댓글을 삭제합니까?')) {
                $.ajax({
                    url: "/board/delete-reply",
                    method: "POST",
                    data: {"replyPk": replyPk},
                    dataType: "json",
                    success: function(receive) {
                        alert(receive.message);
                        if (receive.result == true) {
                            window.location.reload();
                        } else {
                            $('.remove-reply-btn').focus();
                        }
                    }
                });
            }
        });
        
        $('.file-link').on('click', function() {
            var filePk = $(this).data('filePk');
            
            //팝업창 크기
            var popUpWidth = 500
            var popUpHeight = 555;
            //팝업창 위치 조절
            var popUpX = (document.body.offsetWidth / 2) - (popUpWidth / 2);
            //듀얼 모니터인 경우 넣어줘야함.
            popUpX += window.screenLeft;
            var popUpY = (window.screen.height / 2) - (popUpHeight / 2);
            
            window.open('<?php echo $this->url(array('controller' => 'board', 'action' => 'view-image')); ?>?filePk=' + filePk, '이미지 보기', 'scrollbars=no, resizable=no, width=' + popUpWidth + ', height=' + popUpHeight + ', left='+ popUpX + ',top='+ popUpY);
        });
        
        $('.edit-btn').on('click', function() {
            var pk = $(this).data('pk');
        
            window.location.href = '<?php echo $this->url(array('controller' => 'board', 'action' => 'edit'))?>?pk=' + pk;
        });
    });
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 조회 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        게시판 글을 조회합니다.
    </div>
</div>
<div class="view-box">
    <div class="page-header-custom">
        <?php echo $this->escape($board['title']); ?>
        <div class="info">
            <small class="space writer-info">작성자 &emsp; &emsp; : <?php echo $this->escape($board['writer']); ?></small>
        </div>
    </div>
    <div class="text-box">
        <?php echo nl2br($this->escape($board['content'])); ?>
    </div>
    <?php if ($files) : ?>
        <div class="file-info">
            <?php
                foreach ($files as $file) {
                    if (in_array($file['fileType'], $photo)) {
                        echo '<a class="file-link" data-file-pk="'. $file['pk'] .'"><img src="data:image;base64, '. base64_encode($file['content']) .'" alt="image" style="width: 50px; height: 50px;"></a>';
                    } else if ($file['fileType'] == 'pdf') {
                        echo '<a href="' . $this->url(array('controller' => 'board', 'action' => 'file-download')) . '?filePk=' . $file['pk'] . '"><img src="' . $this->baseUrl("/icon/pdf.png") . '" alt="png Icon" width="50px" height="50px"></a>';
                    }
                    
                }
            ?>
        </div>
    <?php endif; ?>
    <div class="time-info">
         <div class="time-left"><strong>등록시간 &emsp; &nbsp; &nbsp; :</strong>&nbsp;&nbsp;<?php echo $this->escape($board['insertTime']); ?></div>
         <div class="time-right"><strong>마지막 수정시간 :</strong>&nbsp; <?php echo $this->escape($board['updateTime']); ?></div>
    </div>
    <div class="reply">
        <div class='reply-title'>댓 &nbsp; 글</div>
        <table class="col-sm-12">
            <thead>
                <tr>
                    <th class="col-sm-1"></th>
                    <th class="col-sm-8"></th>
                    <th class="col-sm-2"></th>
                    <th class="col-sm-1"></th>
                </tr>
            </thead>
            <tbody>
            <?php
                foreach ($replys as $reply) {
                    
                    $select = $memberTabe->select();
                    $select->from($memberTabe->getTableName(), array('name'))->where('pk = ?', $reply['memberPk']);
                    
                    $name = $memberTabe->getAdapter()->fetchRow($select);
            ?>
                <tr>
                   <td class="text-align-left"><strong>· <?php echo $this->escape($name['name']); ?> </strong></td>
                   <td class="text-align-left"><?php echo $this->escape($reply['content']); ?></td>
                   <td><?php echo $this->escape($reply['insertTime']); ?></td>
                   <td>
                       <?php 
                           //게시글 작성자 또는 댓글 작성자만 삭제 버튼 보임
                           if ($board['memberPk'] == $session['storage']->pk || $reply['memberPk'] == $session['storage']->pk) {
                               echo $this->FormButton('remove-reply', 'X', array('class' => 'remove-reply-btn', 'data-reply-pk' => $reply['pk']));
                           }
                       ?>
                   </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    
    <div class="reply-group col-sm-offset-1">
        <?php echo $this->FormText('reply-content', '', array('class' => 'reply-content', 'placeholder' => '댓글을 남겨요')); ?>
        <?php echo $this->FormButton('reply-submit', '등록', array('class' => 'reply-submit', 'data-board-pk' => $board['pk'], 'data-member-pk' => $session['storage']->pk));?>
    </div>
    <div class="view-page-button">
        <?php
        if (($session['storage']->pk == $board['memberPk']) || ($session['storage']->position <= 2)) {
            echo $this->FormButton('delet-btn', '삭 제', array('class' => 'delete-btn', 'data-pk' => $board['pk']));
        }
        ?>
        <div class="button-right">
            <?php
            if ($session['storage']->pk == $board['memberPk']) {
                echo $this->FormButton('edit-btn', '수 정', array('class' => 'submit-btn edit-btn', 'data-pk' => $board['pk']));
            }
            echo $this->FormButton('cancle-btn', '닫 기', array('class' => 'cancle-btn'));
            ?>
        </div>
    </div>
</div>