<?php
$this->headTitle('게시글 작성');
$session = Zend_Session::namespaceGet('Was_Auth');
//hidden input 에 현재 로그인한 유저의 pk 정보 설정
$memberPk = $this->boardForm->getElement('memberPk');
$memberPk->setValue($session['storage']->pk);
?>
<script type="text/javascript">
$(document).ready(function() {
    $('#cancle').on('click', function() {
        window.location.href = "/board/list";
    });
});
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
/*bootstrap3 input file 요소의  display 속성 무효*/
input[type="file"] {
    display: inline;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 작성 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        게시판 글을 작성합니다.
    </div>
</div>
<div class="write-body">
    <form enctype="multipart/form-data" method="<?php echo $this->boardForm->getMethod(); ?>">
        <?php echo $this->boardForm->title; ?>
        <?php echo $this->boardForm->content; ?>
        <?php echo $this->boardForm->writer; ?>
        <div class="form-group">
            <?php echo $this->boardForm->uploadFile; ?>
            <?php echo $this->FormButton('remove-file', 'X', array('class' => 'remove-file-element')); ?>
        </div>
        <?php echo $this->FormButton('add-file', '+', array('class' => 'remove-file-element')); ?>
        <?php echo $this->boardForm->btns; ?>
    </form>
</div>