<?php
$this->headTitle('게시글 작성');
?>
<script type="text/javascript">

</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
/*bootstrap3 input file 요소의  display 속성 무효*/
input[type="file"] {
    display: inline;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 게시판</strong>
        <small>- 작성 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        게시판 글을 작성합니다.
    </div>
</div>
<div class="write-body">
<?php echo $this->boardForm->render(); ?>
</div>