<?php
$this->headTitle('회원관리');
if ($this->position > Was_Member::POWER_MANAGER) {
    echo "<script>alert('관리자가 아닌 회원은 접근할 수 없습니다.');</script>";
    echo "<script>history.back(-1);</script>";
    return;
}

?>
<script type="text/javascript">
    $(document).ready(function() {
        //로그인 제한 체크 박스를 클릭했을 경우의 이벤트
        $(document).on("click", ".authable-btn", function() {
            //누른 체크박스의 data-user-pk를 가져옴
            var userId = $(this).data('userId');
            var checked = $(this).is(":checked");
            if (confirm("로그인 제한 설정을 변경하시겠습니까?")) {
                //action에 ajax 전송
                $.ajax({
                    url: "/manage/authable-manage",
                    method: "POST",
                    data: {"userId": userId, "checked": checked},
                    dataType: "json",
                    success: function(receive) {
                        if (receive.result == true) {
                            alert(receive.message);
                        }
                    }
                });
            } else {
                alert("변경을 취소하셨습니다.");
                if (checked == true) {
                    $(this).prop("checked", false);
                } else {
                    $(this).prop("checked", true);
                }
            }
        });
        
        //관리자 버튼을 누를 경우 동작 처리
        $(document).on("click", ".manager", function() {
            var userId = $(this).data('userId');
            
            if(confirm("등급을 관리자로 변경하시겠습니까?")) {
                $.ajax({
                    url: "/manage/change-manager",
                    method: "POST",
                    data: {"userId": userId},
                    dataType: "json",
                    success: function(receive) {
                        if (receive.result == true) {
                            alert(receive.message);
                            //관리자 버튼을 비활성화하고, 갈색으로 색상 변경
                            $("button[name=manager-" + userId + "]").attr("disabled", true);
                            $("button[name=manager-" + userId + "]").removeClass("gray-color");
                            $("button[name=manager-" + userId + "]").addClass("brown-color");
                            //버튼을 활성화하고, 회색으로 색상 변경
                            $("button[name=normal-" + userId + "]").attr("disabled", false);
                            $("button[name=normal-" + userId + "]").removeClass("green-color");
                            $("button[name=normal-" + userId + "]").addClass("gray-color");
                        } else {
                            alert(receive.message);
                        }
                    }
                });
            } else {
                alert("변경을 취소하셨습니다.");
            }
        });
        
        //일반 버튼을 누를 경우 동작 처리
        $(document).on("click", ".normal", function() {
            var userId = $(this).data('userId');
            
            if(confirm("등급을 일반 회원으로 변경하시겠습니까?")) {
                $.ajax({
                    url: "/manage/change-normal",
                    method: "POST",
                    data: {"userId": userId},
                    dataType: "json",
                    success: function(receive) {
                        if (receive.result == true) {
                            alert(receive.message);
                            //버튼을 활성화하고, 회색으로 색상 변경
                            $("button[name=manager-" + userId + "]").attr("disabled", false);
                            $("button[name=manager-" + userId + "]").removeClass("brown-color");
                            $("button[name=manager-" + userId + "]").addClass("gray-color");
                            //버튼을 비활성화하고, 초록색으로 색상 변경
                            $("button[name=normal-" + userId + "]").attr("disabled", true);
                            $("button[name=normal-" + userId + "]").removeClass("gray-color");
                            $("button[name=normal-" + userId + "]").addClass("green-color");
                        } else {
                            alert(receive.message);
                        }
                    }
                });
            } else {
                alert("변경을 취소하셨습니다.");
            }
        });
        //삭제 버튼을 누를 경우 동작 처리
        $(document).on("click", ".del", function() {
            var userId = $(this).data('userId');
            
            if(confirm("해당 회원 정보를 삭제하겠습니까?")) {
                $.ajax({
                    url: "/manage/delete-member",
                    method: "POST",
                    data: {"userId": userId},
                    dataType: "json",
                    success: function(receive) {
                        if (receive.result == true) {
                            alert(receive.message);
                            window.location.reload();
                        } else {
                            alert(receive.message);
                            window.location.reload();
                        }
                    }
                });
            } else {
                alert("삭제를 취소하셨습니다.");
            }
        });
        //상단 바의 유저 이름을 클릭했을 경우, 수정 창 출력
        $(".user-info").on("click", function() {
            var userId = $(this).data('userId');
            //팝업창 크기
            var popUpWidth = 500
            var popUpHeight = 555;
            //팝업창 위치 조절
            var popUpX = (document.body.offsetWidth / 2) - (popUpWidth / 2);
            //듀얼 모니터인 경우 넣어줘야함.
            popUpX += window.screenLeft;
            var popUpY = (window.screen.height / 2) - (popUpHeight / 2);
            
            window.open('/manage/modify?userId=' + userId, '회원정보수정', 'scrollbars=no, resizable=no, width=' + popUpWidth + ', height=' + popUpHeight + ', left='+ popUpX + ',top='+ popUpY);
        });
        //회원 관리 페이지에서 유저 이름을 클릭했을 경우, 수정 창 출력
        $(".member-name").on("click", function() {
            var userId = $(this).data('userId');
            //팝업창 크기
            var popUpWidth = 500
            var popUpHeight = 555;
            //팝업창 위치 조절
            var popUpX = (document.body.offsetWidth / 2) - (popUpWidth / 2);
            //듀얼 모니터인 경우 넣어줘야함.
            popUpX += window.screenLeft;
            var popUpY = (window.screen.height / 2) - (popUpHeight / 2);
            
            window.open('/manage/modify?userId=' + userId, '회원정보수정', 'scrollbars=no, resizable=no, width=' + popUpWidth + ', height=' + popUpHeight + ', left='+ popUpX + ',top='+ popUpY);
        });
        
        $(".member-search").on("submit", function() {
            $("#search-isSearch").val(1);
        });
    });
    
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 관리자</strong>
        <small>- 회원관리 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        등록 된 회원을 관리하는 페이지 입니다.
    </div>
</div>
<div class="col-sm-12 list-body">
    <?php echo $this->form->render();?>
    <div class="searchCnt"><?php echo number_format($this->recordCount) . " / " . number_format($this->totalCount) . " 건";?></div>
    <table class="myTable">
        <thead class="add-top-line">
            <tr>
                <th class="col-sm-1">회원번호</th>
                <th class="col-sm-2">아이디</th>
                <th class="col-sm-2">회원명</th>
                <th class="col-sm-2">휴대전화번호</th>
                <th class="col-sm-1">로그인제한</th>
                <th class="col-sm-4">작업</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->paginator as $items) { 
            $telNumber = preg_replace("/([0-9]{3})([0-9]{3,4})([0-9]{4})$/","\\1-\\2-\\3" ,$items['telNumber']);
        ?>
            <tr class="add-bottom-line">
                <td><?php echo $items['pk']; ?></td>
                <td class="text-align-left"><?php echo $items['id']; ?></td>
                <td class="text-align-left member-name" data-user-id="<?php echo $items['id']; ?>"><?php echo $items['name']; ?></td>
                <td class="text-align-left"><?php echo $telNumber; ?></td>
                <td>
                    <?php 
                    //checkbox 생성, 4번째 인수인 option에 1일때 checked, 0일때 not checked 를 지정
                    echo $this->FormCheckbox('chkBox', $items['authable'] == 1 ? 0 : 1, array('class' => 'authable-btn', 'data-user-id' => $items['id']), array(1, 0));
                    ?>
                </td>
                <td>
                    <?php 
                    if ($items['position'] == Was_Member::POWER_MEMBER) {
                        //관리자 변경 버튼은 최종 관리자만 보여지도록 if문 사용
                        if ($this->position == Was_Member::POWER_MASTER) {
                            echo $this->FormButton("manager-".$items['id'], '관리자', array('class' => 'common-btn gray-color manager', 'data-user-id' => $items['id']));
                        }
                        echo $this->FormButton("normal-".$items['id'], '일 반', array('class' => 'common-btn green-color normal', 'data-user-id' => $items['id'], 'disabled' => 'disabled'));
                    } else {
                        echo $this->FormButton("manager-".$items['id'], '관리자', array('class' => 'common-btn brown-color manager', 'data-user-id' => $items['id'], 'disabled' => 'disabled'));
                        echo $this->FormButton("normal-".$items['id'], '일 반', array('class' => 'common-btn gray-color normal', 'data-user-id' => $items['id']));
                    }
                    echo $this->FormButton('member-delete', '삭 제', array('class' => 'common-btn red-color del', 'data-user-id' => $items['id']));
                    ?>
                    
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php 
    echo $this->paginationControl($this->paginator, null, null, array('searchForm' => array(
        'category' => $this->form->search->category->getValue(),
        'search'    => $this->form->search->search->getValue(),
    )));
    ?>
</div>
