<?php
$this->headTitle('회원관리');
$session = Zend_Session::namespaceGet('Was_Auth');
if ($session['storage']->position > 2) {
    echo "<script>alert('관리자가 아닌 회원은 접근할 수 없습니다.');</script>";
    echo "<script>history.back(-1);</script>";
    return;
}
?>
<script type="text/javascript">
    $(document).on("click", ".authable-btn", function() {
        //누른 체크박스의 data-user-pk를 가져옴
        var userId = $(this).data('userId');
        var checked = $(this).is(":checked");
        if (confirm("로그인 제한 설정을 변경하시겠습니까?")) {
            //action에 ajax 전송
            $.ajax({
                url: "/manage/authable-manage",
                method: "POST",
                data: {"userId": userId, "checked": checked},
                dataType: "json",
                success: function(receive) {
                    if (receive.result == true) {
                        alert(receive.message);
                    }
                }
            });
        } else {
            alert("변경을 취소하셨습니다.");
            if (checked == true) {
                $(this).prop("checked", false);
            } else {
                $(this).prop("checked", true);
            }
        }
    });
</script>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 관리자</strong>
        <small>- 회원관리 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        등록 된 회원을 관리하는 페이지 입니다.
    </div>
</div>
<div class="col-sm-12 list-body">
    <?php echo $this->form->render();?>
    <div class="searchCnt"><?php echo number_format($this->recordCount) . " / " . number_format($this->totalCount) . " 건";?></div>
    <table class="myTable">
        <thead class="add-top-line">
            <tr>
                <th class="col-sm-1">회원번호</th>
                <th class="col-sm-2">아이디</th>
                <th class="col-sm-2">회원명</th>
                <th class="col-sm-2">휴대전화번호</th>
                <th class="col-sm-1">로그인제한</th>
                <th class="col-sm-4">작업</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->paginator as $items) { 
            $telNumber = preg_replace("/([0-9]{3})([0-9]{3,4})([0-9]{4})$/","\\1-\\2-\\3" ,$items['telNumber']);
        ?>
            <tr class="add-bottom-line">
                <td><?php echo $items['pk']; ?></td>
                <td class="text-align-left"><?php echo $items['id']; ?></td>
                <td class="text-align-left"><?php echo $items['name']; ?></td>
                <td class="text-align-left"><?php echo $telNumber; ?></td>
                <td>
                    <?php 
                    //checkbox 생성, 4번째 인수인 option에 1일때 checked, 0일때 not checked 를 지정
                    echo $this->FormCheckbox('chkBox', $items['authable'] == 1 ? 0 : 1, array('class' => 'authable-btn', 'data-user-id' => $items['id']), array(1, 0));
                    ?>
                </td>
                <td>
                    <?php if ($items['position'] == 3) {
                        echo $this->FormButton('manager', '관리자', array('class' => 'manager-btn gray-color', 'data-user-id' => $items['id']));
                        echo $this->FormButton('normal', '일 반', array('class' => 'normal-btn green-color', 'data-user-id' => $items['id'], 'disabled' => 'disabled'));
                    } else {
                        echo $this->FormButton('manager', '관리자', array('class' => 'manager-btn brown-color', 'data-user-id' => $items['id'], 'disabled' => 'disabled'));
                        echo $this->FormButton('normal', '일 반', array('class' => 'normal-btn gray-color', 'data-user-id' => $items['id']));
                    }
                    echo $this->FormButton('member-delete', '삭 제', array('class' => 'delete-btn', 'data-user-id' => $items['id']));
                    ?>
                    
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php 
    echo $this->paginator->render();
    ?>
</div>
