<?php
$this->headTitle('회원관리');
?>
<style type="text/css">
.list-title strong {
    color: #595959;
}

.list-title small {
    color: #8497B0;
}
</style>
<div class="col-sm-12">
    <div class="list-title">
        <strong>씨엠에스코리아 관리자</strong>
        <small>- 회원관리 -</small>
    </div>
    <div class="col-sm-12 list-descript">
        등록 된 회원을 관리하는 페이지 입니다.
    </div>
</div>
<div class="col-sm-12 list-body">
    <?php echo $this->form->render();?>
    <div class="searchCnt"><?php echo number_format($this->recordCount) . " / " . number_format($this->totalCount) . " 건";?></div>
    <table class="myTable">
        <thead class="add-top-line">
            <tr>
                <th class="col-sm-2">회원번호</th>
                <th class="col-sm-2">아이디</th>
                <th class="col-sm-2">회원명</th>
                <th class="col-sm-2">휴대전화번호</th>
                <th class="col-sm-1">로그인제한</th>
                <th class="col-sm-3">작업</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->paginator as $items) { 
            $telNumber = preg_replace("/([0-9]{3})([0-9]{3,4})([0-9]{4})$/","\\1-\\2-\\3" ,$items['telNumber']);
        ?>
            <tr class="add-bottom-line">
                <td><?php echo $items['pk']; ?></td>
                <td class="text-align-left"><?php echo $items['id']; ?></td>
                <td class="text-align-left"><?php echo $items['name']; ?></td>
                <td class="text-align-left"><?php echo $telNumber; ?></td>
                <td><?php echo $items['authable']; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php 
    echo $this->paginator->render();
    ?>
</div>
