<?php
$this->headTitle("회원수정");
//렌더링 시킬 form의 개행문자를 제거.(한줄로 입력하기 위해서)
$pwForm = preg_replace('/\r\n|\r|\n/','', $this->pwForm->render());
?>
<script type="text/javascript">
$(document).ready(function() {
    <?php if (isset($this->message)) : ?>
    var message = '<?php echo $this->message; ?>';
    alert(message);
    window.close();
    <?php endif;?>
    
    //개행문자 제거한 form 문자열 추가
    var formElement = '<?php echo $pwForm;?>';
    $(".change-pw-btn").after(formElement);
    
    //현재 비밀번호가 일치하는 지 체크하는 변수. default 는 true;
    var pwOk = true;
    var userId = '<?php echo $this->userId ?>';
    
    //비밀번호 변경 버튼 누를시, 비밀번호 변경 form이 보이도록 변경
    $(".change-pw-btn").on("click", function() {
        pwOk = false;
        //비밀번호 입력 form 이 보이도록 속성 변경
        $(".pwPart").removeClass("display-none");
        $(".pwPart").addClass("display-block");
        //버튼 제거
        $(this).remove();
        //title css 속성 변경
        $("div[name=title]").removeClass("title-before");
        $("div[name=title]").addClass("title-after");
    });
    
    //제출 버튼 초기 배경색 설정
    $(".submit-btn").addClass("submit-gray-color");
    
    //비밀번호 입력창이 떴는지 확인
    if ($(".pwPart").length) {
        //초기 비밀번호 변경, 확인 배경색 및 readonly 적용
        $("#newPw").addClass("background-gray");
        $("#confirmPw").addClass("background-gray");
        $("#newPw").attr("readonly", true);
        $("#confirmPw").attr("readonly", true);
        $("#newPw").attr("disabled", true);
        $("#confirmPw").attr("disabled", true);
        //현재 비밀번호 입력할 때마다 감지, 확인
        $("#nowPw").on("keyup", function() {
            var nowPw = $(this).val();
            //기존 비밀번호 미입력시, 비밀번호를 변경하지 않는 것으로 간주
            if (nowPw == '') {
                pwOk = true;
            } else {
                pwOk = false;
            }
            
            $.ajax({
                url: "/manage/check-pw",
                data: {"nowPw": nowPw, "userId": userId},
                dataType: "json",
                method: "POST",
                success: function(receive) {
                    if (receive.result == true) {
                        //입력된 비밀번호 값이 현재 비밀번호와 일치하는 경우, 변경, 확인을 입력할 수 있도록 설정
                        $("#newPw").removeClass("background-gray");
                        $("#confirmPw").removeClass("background-gray");
                        $("#newPw").attr("readonly", false);
                        $("#confirmPw").attr("readonly", false);
                        $("#newPw").attr("disabled", false);
                        $("#confirmPw").attr("disabled", false);
                    } else {
                        //일치하지 않거나, 현재 비밀번호를 지운 경우, 초기 설정으로 변경, 입력한 값 초기화
                        $("#newPw").addClass("background-gray");
                        $("#confirmPw").addClass("background-gray");
                        $("#newPw").attr("readonly", true);
                        $("#confirmPw").attr("readonly", true);
                        $("#newPw").attr("disabled", true);
                        $("#confirmPw").attr("disabled", true);
                        $("#newPw").val("");
                        $("#confirmPw").val("");
                    }
                }
            });
        });
    }
    
    //비밀번호 확인 입력창 입력시, 변경창의 입력값과 동일한 지 실시간 비교
    $("#confirmPw").on("keyup", function() {
        if($("#newPw").val() != '' && ($("#newPw").val() == $("#confirmPw").val())) {
            pwOk = true;
        } else {
            pwOk = false;
        }
    });
    
    //입력값이 모두 입력됐는지 체크하는 변수
    var isEmpty = true;
    //각 input이 변경되었을 때 실행
    $(".signup-form").find("input[type=text]").change(function() {
        var Elements = $(".signup-form input[type=text]");
        for (var i = 0; i < Elements.length - 1; i++) {
            //비어있지 않으면 false 입력, 비어있으면 true 입력
            if ($(Elements[i]).val() != "" && $(Elements[i]).val() != null) {
                isEmpty = false;
            } else {
                isEmpty = true;
                break;
            }
        }
        //입력값이 모두 들어있고, 아이디 중복체크를 통과했으면 제출 비활성화 해제 
        if (!isEmpty && pwOk) {
            $(".submit-btn").attr("disabled", false);
            $(".submit-btn").removeClass("submit-gray-color");
            $(".submit-btn").addClass("submit-green-color");
        } else {
            $(".submit-btn").attr("disabled", true);
            $(".submit-btn").removeClass("submit-green-color");
            $(".submit-btn").addClass("submit-gray-color");
        }
    });
});
</script>
<div class="center">
    <div class="col-sm-12 fence">
        <div class="member-modify-title title-before" name="title">
            <strong>씨엠에스코리아 게시판</strong><small class="subtitle">- 회원수정 -</small>
        </div>
        <?php
            echo $this->modifyForm->render();
        ?>
    </div>
</div>