<div class="menubar">
    <div class="menutitle"><a href="/board/list">CMSKOREA Board</a></div>
    <div class="info-group">
        <div class="user-info" data-user-id="<?php echo $this->id; ?>"><?php echo $this->name; ?></div>
        <?php
        if ($this->position != 3) {
            $managetUrl = $this->url(array('controller' => 'manage', 'action' => 'manage', 'page' => 1));
            echo $this->FormButton('member-manage', '회원관리', array('class' => 'logout-btn', 'onclick' => "location.href='{$managetUrl}'"));
        }
            $logoutUrl = $this->url(array('controller' => 'login', 'action' => 'logout'));
            echo $this->FormButton('logout', '로그아웃', array('class' => 'logout-btn', 'onclick' => "location.href='{$logoutUrl}'"));
        ?>
    </div>
</div>