<?php
$this->headTitle('아이디 찾기');
?>
<script type="text/javascript">
$(document).ready(function() {
    <?php if (isset($this->processResult)) : ?>
        var processResult = '<?php echo $this->processResult ? 'true' : 'false'; ?>';
        var processId = '<?php echo $this->processId; ?>';
        
        //존재하지 않는 회원일 시, 경고창만 출력
        if (processResult == 'false') {
            alert(processId);
        } else if (processResult == 'true') {
            //존재하는 회원일 시
            //form 및 텍스트 삭제
            $('div.des-padding').remove();
            $('form.search-form').remove();
            //아이디 찾기 결과를 보여주기 위해 새 요소 삽입 및 전시
            $(".field").append("<div class='search-result'>검색 결과</div>");
            $(".field").append("<div class='searched-id'>" + processId + "</div>");
            $(".field").append("<div class='search-description'>위의 아이디를 복사하실 수 있습니다.</div>");
        }
    <?php endif; ?>
    
    //아이디 찾기 버튼 클릭했을 때, 먼저 입력값 형식 확인
    $(".search-form").on("submit", function() {
        var name = $("#name").val();
        var tel = $("#telNumber").val();
        var nameReg = /[가-힣A-Za-z]+$/;
        var telReg = /^01(0|1|6|7|8|9)-?([0-9]{3,4})-?([0-9]{4})$/;
        //제출 누를 시, 올바른 형식으로 입력했는 지 확인
        if (name == '' || tel == '') {
            alert('이름, 휴대전화번호를 모두 입력해주세요.');
            return false;
        }
        
        if (!nameReg.test(name) || !telReg.test(tel)) {
            alert('이름 또는 휴대전화번호가 잘못된 형식입니다.');
            return false;
        }
    });
});
</script>
<style type="text/css">
.search-background {
    background-color: #E7E6E6;
}
</style>
<div class="container center">
    <div class="col-sm-6 search-background">
        <div class="text-center">
            <div class="sep-line">
               <strong>CMSKOREA Board</strong>
            </div>
            <div class="des-padding">이름 / 휴대전화번호를 입력하여 주세요.</div>
        </div>
        <?php
            //form rendering
            echo $this->form->render(); 
        ?>
        <div>
        <?php 
            echo $this->FormButton('back', '돌아가기', array('class' => 'back-btn', 'onclick' => "location.href='signin'"));
        ?>
        </div>
    </div>
</div>