<?php
$this->headTitle("로그인");
//이미 로그인한 경우, 게시글 리스트로 리다이렉트
if (Zend_Session::namespaceGet('Was_Auth')) {
    echo "<script type=\"text/javascript\">alert('이미 로그인하셨습니다.');</script>";
    echo "<script type=\"text/javascript\">location.href='/board/boardlist';</script>";
}
?>
<script type="text/javascript">
    $(document).ready(function(){
        <?php if (isset($this->processResult)) : ?>
        var processResult = <?php echo $this->processResult ? 'true' : 'false'; ?>;
        var processMessage = '<?php echo $this->processMessage; ?>';
        
        if (!processResult && processMessage != '') {
            alert(processMessage);
        }
        <?php endif;?>
        
        //저장된 쿠키값을 가져와서 id 입력칸에 삽입. 없으면 공백 삽입
        var key = getCookie("key");
        $("#id").val(key);
        
        //id 를 저장하고 페이지 로딩 시, 입력칸에 저장된 id가 표시된 상태라면 체크박스 체크 유지
        if ($("#id").val() != "") {
            $("#isSaveId").attr("checked", true);
        }
        
        //체크 박스 변화 확인
        $("#isSaveId").change(function(){
            //체크되었을 때
            if ($("#isSaveId").is(":checked")) {
                //7일동안 쿠키 보관
                setCookie("key", $("#id").val(), 7);
            } else {
                //체크 해제시 쿠키 삭제
                deleteCookie("key");
            }
        });
        
        $("#id").keyup(function(){
            if ($("#isSaveId").is(":checked")) {
                setCookie("key", $("#id").val(), 7);
            }
        });
        //로그인 유효성 체크
        $(".loginForm").on("submit", function() {
        	var id = $("#id").val();
            var pw = $("#pw").val();
            var idReg = /^[a-zA-Z0-9]*$/;
            var pwReg = /(?=.*[~`!@#$%\^&*()-+=])[A-Za-z0-9~`!@#$%\^&*()-+=]+$/;
            
            if (id == '' || pw == '') {
                alert("아이디 또는 비밀번호를 입력해주세요.");
                return false;
            }
            if (!idReg.test(id) || !pwReg.test(pw)) {
                alert("아이디 또는 비밀번호의 형식이 맞지않습니다.");
                return false;
            }
        });
    });
    
    //쿠키 저장하기
    function setCookie(cookieName, value, expireDays) {
        //현재시각 저장
        var expireDate = new Date();
        //현재 몇 일인지 확인후, 설정한 만료 일자를 더해서 지정 (현재 월 시작일 + 지정날짜)
        expireDate.setDate(expireDate.getDate() + expireDays);
        //GMT 포멧으로 설정
        var cookieValue = escape(value) + ((expireDays == null) ? "" : "; expires=" + expireDate.toGMTString());
        document.cookie = cookieName + "=" + cookieValue;
    }
    
    //쿠키 삭제
    function deleteCookie(cookieName) {
        var expireDate = new Date();
        expireDate.setDate(expireDate.getDate() - 1);
        document.cookie = cookieName + "= " + "; expires=" + expireDate.toGMTString();
    }
    
    //쿠키 가져오기
    function getCookie(cookieName) {
        cookieName = cookieName + '=';
        
        var cookieData = document.cookie;
        var start = cookieData.indexOf(cookieName);
        var cookieValue = '';
        
        if (start != -1) {
            start += cookieName.length;
            var end = cookieData.indexOf(';', start);
            if (end == -1) {
                end = cookieData.length;
            }
            cookieValue = cookieData.substring(start, end);
        }
        
        return unescape(cookieValue);
    }
    
    //팝업창 전시
    function popUp() {
        //팝업창 크기
        var popUpWidth = 500
        var popUpHeight = 555;
        //팝업창 위치 조절
        var popUpX = (document.body.offsetWidth / 2) - (popUpWidth / 2);
        //듀얼 모니터인 경우 넣어줘야함.
        popUpX += window.screenLeft;
        var popUpY = (window.screen.height / 2) - (popUpHeight / 2);
        
        window.open('signup', '회원가입', 'scrollbars=no, resizable=no, width=' + popUpWidth + ', height=' + popUpHeight + ', left='+ popUpX + ',top='+ popUpY);
    }
</script>
<div class="container center">
    <div class="col-sm-6" style="background-color: rgb(231, 230, 230);">
        <div class="text-center">
            <div class="sep-line">
               <strong>CMSKOREA Board</strong>
            </div>
            <div class="des-padding">아이디 / 비밀번호를 입력해 주세요.</div>
        </div>
        <?php
            //form rendering
            echo $this->form->render(); 
        ?>
        <div class="login-bottom">
            <div class="checks">
                <?php echo $this->FormCheckbox('isSaveId', 'no', array('class' => 'hello')); ?>
                <label for="isSaveId" class="chkText"><span>아이디 저장</span></label>
                <div class="links">
                <?php 
                    echo $this->FormButton('signUp', '회원가입', array('class' => 'signup-btn', 'onclick' => "popUp();"));
                    echo $this->FormButton('searchId', '아이디찾기', array('class' => 'searchId-btn', 'onclick' => "alert('점검중')"));
                ?>
                </div>
            </div>
        </div><!-- login-bottom end -->
    </div><!-- login window end -->
</div>

