<div class="pagination-class">
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
        <a class="front-and-back" href="<?php echo $this->url(array('page' => $this->first)); ?>">First</a>
    <?php else: ?>
        <span class="disabled front-and-back disable-btn">First</span>
    <?php endif; ?>
 
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <a class="page-btn active-color" href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; </a>
    <?php else: ?>
        <span class="disabled page-btn">&lt;</span>
    <?php endif; ?>
    
    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <a class="page-btn" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
        <?php else: ?>
            <span class="page-btn current-page"><?php echo $page; ?></span>
        <?php endif; ?>
     <?php endforeach; ?>
     
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <a class="page-btn active-color" href="<?php echo $this->url(array('page' => $this->next)); ?>">&gt;</a>
    <?php else: ?>
        <span class="disabled page-btn">&gt;</span>
    <?php endif; ?>
    
    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
        <a class="front-and-back active-color" href="<?php echo $this->url(array('page' => $this->last)); ?>">Last</a>
    <?php else: ?>
        <span class="disabled front-and-back disable-btn">Last</span>
    <?php endif; ?>
</div>
